### ISSUE TITLE
Checking layer using keyboard gets rid of focus

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/MapML.js#1007]
Steps to reproduce:
1. go to https://maps4html.org/experiments/screenreader/restaurants/
2. Navigate to the layer control by pressing tab and open it
3. uncheck the layer

Expected outcome: the focus should stay on the checkbox, but instead the focus disappears from the layer control until you press tab again.

**Comment by prushforth** [comment]
Yeah that's not good

**Comment by prushforth** [comment]
I found that using keyboard if you uncheck, then tab, it focuses the checkbox again, so it's not going far.  But it should stay put imho.
