### ISSUE TITLE
Should untitled layers be exposed in the layer list UI?

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML.js#319]
Modifying [us_pop_density.mapml](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/master/test/e2e/data/tiles/cbmt/us_pop_density.mapml) (used in e.g. keyboardInteraction.html) results in the following:

```html
<title><!--US Population Density--></title>
```` 

![empty-title](https://user-images.githubusercontent.com/26493779/109164941-48bd9980-777b-11eb-85ea-f74f78c2473f.png)

```html
<!--<title>US Population Density</title>-->
```` 
![no-title](https://user-images.githubusercontent.com/26493779/109164944-48bd9980-777b-11eb-97c0-d1ecfdfef1b3.png)

Should untitled layers be visible in the layer list?

**Comment by Malvoz** [comment]
FWIW given the following HTML:

```html
<select>
  <option></option>
</select>
```
does result in an empty option (tested in Chrome and Firefox):

![empty-option](https://user-images.githubusercontent.com/26493779/109167874-896ae200-777e-11eb-918d-3cbf35c270c9.png)

**Comment by prushforth** [comment]
I think untitled/labelled layers should be presented,  because you can hide layers you don't want shown by adding the `hidden` attribute.  I do think they could have a generated "Map Layer" or some such, so that screen readers would say them.  TBD how well this [layer control](https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/263) works for screen readers.

**Comment by AliyanH** [comment]
Currently, when GeoJSON layers (with no label) are pasted to the mapml-viewer, they get a default [localized name](https://github.com/Maps4HTML/mapml-extension/pull/47) of "Layer". I wonder if the same semantics should be used for untitled/unlabeled layers.

For ex. Pasting the following geojson to a [mapml-viewer](https://maps4html.org/experiments/screenreader/restaurants/) results in a new layer with the "Layer" label:
`{ "type": "FeatureCollection", "features": [ { "type": "Feature", "properties": {}, "geometry": { "coordinates": [ [ -75.70390559334825, 45.4080260348249 ], [ -75.68642173896234, 45.428944769710455 ] ], "type": "LineString" } } ] }`
