### ISSUE TITLE
Some components currently don't take advantage of L.options.locale

### ISSUE THREAD

**Issue by ahmadayubi** [Maps4HTML/MapML.js#568]
Currently the following components don't use `M.options.locale`:

- zoom buttons
- full screen button

This prevents translation to the user agents language of preference through the mapml-extension. Feel free to add other componenets that could also benefit from using `L.options.locale`.

**Comment by Malvoz** [comment]
Other components include:

Map:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/1111728f186d5229d0bb5d99264fdac060f8bd17/src/mapml-viewer.js#L224

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/1111728f186d5229d0bb5d99264fdac060f8bd17/src/web-map.js#L261

Layer control:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L516

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L527

Popup navigation controls:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L1252

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L1264

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L1278

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/e8132d4787311e9a2fa16bff186dbeeb093466fa/src/mapml/layers/MapLayer.js#L1287

Features:

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/1111728f186d5229d0bb5d99264fdac060f8bd17/src/mapml/layers/FeatureLayer.js#L267

https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/1111728f186d5229d0bb5d99264fdac060f8bd17/src/mapml/layers/TemplatedFeaturesLayer.js#L137

**Comment by Malvoz** [comment]
Also:

- Layer control's `title="Layers"`
- Popup's close button (actually missing an accessible name altogether, tracked in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/247#popups, the 3rd item)

**Comment by prushforth** [comment]
Closing, because I believe all these issues were resolved by [this commit](https://github.com/Maps4HTML/MapML.js/commit/56a87912b3a4dc4d6ed3ecb7a1b53407895640e9) as well as [recent commits in the mapml-extension](https://github.com/search?q=repo%3AMaps4HTML%2Fmapml-extension+locale&type=pullrequests)
