### ISSUE TITLE
map-extent add zoomTo() method, extent property and map-change event 

### ISSUE THREAD

**Issue by AliyanH** [Maps4HTML/MapML.js#907]
Add the following to map-extent to be similar to `layer-`
- [x] extent property
- [x] zoomTo() method
- [ ] map-change event 
- [ ] Document the above on web-map-doc

**Comment by prushforth** [comment]
Remind me: What does the map-change event relate to ?  IIRC it's analog on the platform is the [change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event):

_The change event is fired for [\<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [\<select>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), and [\<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) elements when the user modifies the element's value. Unlike the [input](https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event) event, the change event is not necessarily fired for each alteration to an element's value._

So when we do implement the `map-change` event, it gives us the opportunity to amend the behaviour that we currently implement (I believe) which is that the event is fired for each alteration to the checked status, regardless of whether that change was programmatic or user-initiated.  I  may be mixing stuff up.

**Comment by AliyanH** [comment]
> What does the map-change event relate to ?

It is referring to the event fired off by the checked attribute, like we have for layer - https://maps4html.org/web-map-doc/docs/api/layer-api#events
