### ISSUE TITLE
Rename / rebrand as the "MapML polyfill"

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML.js#964]
Possibilities:

- \@maps4html/MapML.js
- ~\@maps4html/Maple.js~ 
- ~\@maps4html/maple-elements~

Tasks:

- [x] find and replace 'web-map-custom-element' across:  web-map-custom-element, web-map-doc, experiments, mapml-extension, explainer, tbd
- [x] deal with npm, unpkg etc
- [x] update readme for MapML.js, to talk about what MapML stands for.
- [x] rename Maps4HTML/MapML repository to Maps4HTML/MapML-Specification
- [x] update geoserver documentation
- [x] update geo.ca references
- [x] blog about it

**Comment by AliyanH** [comment]
in progress...

**Comment by prushforth** [comment]
I think we can safely start referring to this library as the "MapML polyfill" and hopefully things will go smoothly from here.

**Comment by prushforth** [comment]
Having spent a bunch of time bundling project artifacts into a single .js file plus a single .css file, it seems logical to make those files be named mapml.js and mapml.css, respectively.  This would conform to some expectations set up by the new name of the project (MapML.js).  

When we make a new release of this change, we will need to identify all of our web pages that rely on mapml-viewer.js on CDN and update them to rely on the new module name instead.
